create extension if not exists postgis with schema extensions;

create table if not exists public.thua_dat (
    id bigint generated by default as identity primary key,
    ma_xa text not null,
    so_to integer not null,
    so_thua integer not null,
    muc_dich_su_dung text,
    dien_tich double precision,
    ten_chu text,
    dia_chi text,
    geom extensions.geometry(Polygon, 4326) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint thua_dat_ma_xa_so_to_so_thua_key unique (ma_xa, so_to, so_thua)
);

create index if not exists thua_dat_geom_gix
    on public.thua_dat using gist (geom);

create index if not exists thua_dat_tra_cuu_idx
    on public.thua_dat (ma_xa, so_to, so_thua);

alter table public.thua_dat enable row level security;

drop policy if exists "Cho phép đọc thửa đất" on public.thua_dat;
create policy "Cho phép đọc thửa đất"
    on public.thua_dat
    for select
    to anon, authenticated
    using (true);

