create extension if not exists postgis with schema extensions;

create table if not exists public.thua_dat (
    id bigint generated by default as identity primary key,
    ma_xa text not null,
    so_to integer not null,
    so_thua integer not null,
    muc_dich_su_dung text,
    dien_tich double precision,
    ten_chu text,
    dia_chi text,
    geom extensions.geometry(Polygon, 4326) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint thua_dat_ma_xa_so_to_so_thua_key unique (ma_xa, so_to, so_thua)
);

create index if not exists thua_dat_geom_gix
    on public.thua_dat using gist (geom);

create index if not exists thua_dat_tra_cuu_idx
    on public.thua_dat (ma_xa, so_to, so_thua);

alter table public.thua_dat enable row level security;

drop policy if exists "Cho phép đọc thửa đất" on public.thua_dat;
create policy "Cho phép đọc thửa đất"
    on public.thua_dat
    for select
    to anon, authenticated
    using (true);

create table if not exists public.dong_bo_du_lieu (
    id bigint generated by default as identity primary key,
    ma_xa text not null,
    so_to integer not null,
    so_thua integer not null,
    da_xuat_so_dia_chinh_dien_tu boolean not null default false,
    chua_xuat_so_dia_chinh_dien_tu boolean not null default false,
    dong_bo_3_khoi boolean not null default false,
    khong_dong_bo_3_khoi boolean not null default false,
    chi_co_du_lieu_thuoc_tinh boolean not null default false,
    khop_csdlqg_dan_cu boolean not null default false,
    chua_khop_csdlqg_dan_cu boolean not null default false,
    khong_xac_dinh_csdlqg_dan_cu boolean not null default false,
    van_hanh_24_7 boolean not null default false,
    khong_van_hanh_24_7 boolean not null default false,
    phan_loai_ke_hoach_2959 text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint dong_bo_du_lieu_ma_xa_so_to_so_thua_key unique (ma_xa, so_to, so_thua)
);

create index if not exists dong_bo_du_lieu_tra_cuu_idx
    on public.dong_bo_du_lieu (ma_xa, so_to, so_thua);

alter table public.dong_bo_du_lieu enable row level security;

drop policy if exists "Cho phép đọc đồng bộ dữ liệu" on public.dong_bo_du_lieu;
create policy "Cho phép đọc đồng bộ dữ liệu"
    on public.dong_bo_du_lieu
    for select
    to anon, authenticated
    using (true);

-- =========================================================
-- LẤY/ĐẾM THỬA THEO KHUNG BẢN ĐỒ (dùng cho /api/parcels,
-- /api/parcels/count ở backend — kể cả tính năng "quanh vị trí của tôi").
--
-- Trước đây 2 hàm này chỉ được tạo tay trực tiếp trong Supabase, không có
-- trong file này. Nay bổ sung lại đầy đủ, kèm p_nhom để lọc theo phân loại
-- KH 2959 (giống search_parcels bên dưới).
-- =========================================================

drop function if exists public.count_parcels_in_view(
    double precision, double precision, double precision, double precision, text
);
drop function if exists public.count_parcels_in_view(
    double precision, double precision, double precision, double precision, text, text
);

create or replace function public.count_parcels_in_view(
    p_west double precision,
    p_south double precision,
    p_east double precision,
    p_north double precision,
    p_ma_xa text default null,
    p_nhom text[] default null
)
returns integer
language sql
stable
as $$
    select count(*)::integer
    from public.thua_dat t
    left join public.dong_bo_du_lieu d
        on d.ma_xa = t.ma_xa and d.so_to = t.so_to and d.so_thua = t.so_thua
    where t.geom && ST_MakeEnvelope(p_west, p_south, p_east, p_north, 4326)
      and (p_ma_xa is null or t.ma_xa = p_ma_xa)
      and (
          p_nhom is null or array_length(p_nhom, 1) is null
          or (
              'DEFAULT' = any(p_nhom)
              and (d.id is null or coalesce(trim(d.phan_loai_ke_hoach_2959), '') = '')
          )
          or upper(trim(d.phan_loai_ke_hoach_2959)) in (
              select upper(trim(x)) from unnest(p_nhom) as x
          )
      );
$$;

grant execute on function public.count_parcels_in_view(
    double precision, double precision, double precision, double precision, text, text[]
) to anon, authenticated;

drop function if exists public.get_parcels_in_view(
    double precision, double precision, double precision, double precision,
    double precision, double precision, integer, integer, text, double precision
);
drop function if exists public.get_parcels_in_view(
    double precision, double precision, double precision, double precision,
    double precision, double precision, integer, integer, text, double precision, text
);

create or replace function public.get_parcels_in_view(
    p_west double precision,
    p_south double precision,
    p_east double precision,
    p_north double precision,
    p_center_lng double precision,
    p_center_lat double precision,
    p_limit integer default 1000,
    p_offset integer default 0,
    p_ma_xa text default null,
    p_simplify double precision default 0,
    p_nhom text[] default null
)
returns jsonb
language sql
stable
security definer
set search_path = public, extensions
as $$
    select jsonb_build_object(
        'type', 'FeatureCollection',
        'features', coalesce(jsonb_agg(feature), '[]'::jsonb)
    )
    from (
        select jsonb_build_object(
            'type', 'Feature',
            'id', t.id,
            'geometry', ST_AsGeoJSON(
                case when p_simplify > 0
                     then ST_SimplifyPreserveTopology(t.geom, p_simplify)
                     else t.geom
                end
            )::jsonb,
            'properties', jsonb_build_object(
                'ma_xa', t.ma_xa,
                'so_to', t.so_to,
                'so_thua', t.so_thua,
                'muc_dich_su_dung', t.muc_dich_su_dung,
                'dien_tich', t.dien_tich,
                'ten_chu', t.ten_chu,
                'dia_chi', t.dia_chi,
                'dong_bo', case when d.id is null then null else jsonb_build_object(
                    'da_xuat_so_dia_chinh_dien_tu', d.da_xuat_so_dia_chinh_dien_tu,
                    'chua_xuat_so_dia_chinh_dien_tu', d.chua_xuat_so_dia_chinh_dien_tu,
                    'dong_bo_3_khoi', d.dong_bo_3_khoi,
                    'khong_dong_bo_3_khoi', d.khong_dong_bo_3_khoi,
                    'chi_co_du_lieu_thuoc_tinh', d.chi_co_du_lieu_thuoc_tinh,
                    'khop_csdlqg_dan_cu', d.khop_csdlqg_dan_cu,
                    'chua_khop_csdlqg_dan_cu', d.chua_khop_csdlqg_dan_cu,
                    'khong_xac_dinh_csdlqg_dan_cu', d.khong_xac_dinh_csdlqg_dan_cu,
                    'van_hanh_24_7', d.van_hanh_24_7,
                    'khong_van_hanh_24_7', d.khong_van_hanh_24_7,
                    'phan_loai_ke_hoach_2959', d.phan_loai_ke_hoach_2959
                ) end,
                -- Thửa đã có dữ liệu GCN (bảng public.du_lieu_gcn, đối chiếu qua
                -- khóa madvhc_soto_sothua — xem sync_gcn/create_du_lieu_gcn.sql).
                -- Hàm chạy security definer để bỏ qua RLS của du_lieu_gcn (chỉ
                -- service role đọc trực tiếp được) mà vẫn chỉ lộ ra 1 cờ boolean,
                -- không lộ dữ liệu cá nhân trong bảng đó.
                'co_gcn', exists (
                    select 1
                    from public.du_lieu_gcn g
                    where g.madvhc_soto_sothua
                        = t.ma_xa || '_' || t.so_to::text || '_' || t.so_thua::text
                )
            )
        ) as feature
        from public.thua_dat t
        left join public.dong_bo_du_lieu d
            on d.ma_xa = t.ma_xa and d.so_to = t.so_to and d.so_thua = t.so_thua
        where t.geom && ST_MakeEnvelope(p_west, p_south, p_east, p_north, 4326)
          and (p_ma_xa is null or t.ma_xa = p_ma_xa)
          and (
              p_nhom is null or array_length(p_nhom, 1) is null
              or (
                  'DEFAULT' = any(p_nhom)
                  and (d.id is null or coalesce(trim(d.phan_loai_ke_hoach_2959), '') = '')
              )
              or upper(trim(d.phan_loai_ke_hoach_2959)) in (
                  select upper(trim(x)) from unnest(p_nhom) as x
              )
          )
        order by t.geom <-> ST_SetSRID(ST_MakePoint(p_center_lng, p_center_lat), 4326)
        limit p_limit offset p_offset
    ) features;
$$;

grant execute on function public.get_parcels_in_view(
    double precision, double precision, double precision, double precision,
    double precision, double precision, integer, integer, text, double precision, text[]
) to anon, authenticated;

-- =========================================================
-- BỘ LỌC TRA CỨU: mã xã (bắt buộc) + nhóm + số tờ + số thửa
-- Dùng cho /api/parcels/xa-list và /api/parcels/search ở backend.
-- Khác get_parcels_in_view: không lọc theo khung bản đồ, luôn yêu cầu
-- mã xã để tránh quét toàn tỉnh.
-- =========================================================

create or replace function public.list_ma_xa()
returns table (ma_xa text)
language sql
stable
as $$
    select distinct t.ma_xa
    from public.thua_dat t
    order by t.ma_xa;
$$;

grant execute on function public.list_ma_xa() to anon, authenticated;

-- Danh sách mã xã kèm tên xã (bảng public.danhsachxaphuong) để combobox
-- hiển thị tên cho dễ nhận biết, còn tra cứu vẫn dùng mã xã.
create or replace function public.list_xa_phuong()
returns table (ma_xa text, ten_xa text)
language sql
stable
as $$
    select x.ma_xa, x.ten_xa
    from public.danhsachxaphuong x
    order by x.ten_xa;
$$;

grant execute on function public.list_xa_phuong() to anon, authenticated;

drop function if exists public.search_parcels(
    text, text, integer, integer, integer, integer, double precision
);

create or replace function public.search_parcels(
    p_ma_xa text,
    p_nhom text[] default null,
    p_so_to integer default null,
    p_so_thua integer default null,
    p_limit integer default 1000,
    p_offset integer default 0,
    p_simplify double precision default 0
)
returns jsonb
language sql
stable
security definer
set search_path = public, extensions
as $$
    select jsonb_build_object(
        'type', 'FeatureCollection',
        'features', coalesce(jsonb_agg(feature), '[]'::jsonb)
    )
    from (
        select jsonb_build_object(
            'type', 'Feature',
            'id', t.id,
            'geometry', ST_AsGeoJSON(
                case when p_simplify > 0
                     then ST_SimplifyPreserveTopology(t.geom, p_simplify)
                     else t.geom
                end
            )::jsonb,
            'properties', jsonb_build_object(
                'ma_xa', t.ma_xa,
                'so_to', t.so_to,
                'so_thua', t.so_thua,
                'muc_dich_su_dung', t.muc_dich_su_dung,
                'dien_tich', t.dien_tich,
                'ten_chu', t.ten_chu,
                'dia_chi', t.dia_chi,
                'dong_bo', case when d.id is null then null else jsonb_build_object(
                    'da_xuat_so_dia_chinh_dien_tu', d.da_xuat_so_dia_chinh_dien_tu,
                    'chua_xuat_so_dia_chinh_dien_tu', d.chua_xuat_so_dia_chinh_dien_tu,
                    'dong_bo_3_khoi', d.dong_bo_3_khoi,
                    'khong_dong_bo_3_khoi', d.khong_dong_bo_3_khoi,
                    'chi_co_du_lieu_thuoc_tinh', d.chi_co_du_lieu_thuoc_tinh,
                    'khop_csdlqg_dan_cu', d.khop_csdlqg_dan_cu,
                    'chua_khop_csdlqg_dan_cu', d.chua_khop_csdlqg_dan_cu,
                    'khong_xac_dinh_csdlqg_dan_cu', d.khong_xac_dinh_csdlqg_dan_cu,
                    'van_hanh_24_7', d.van_hanh_24_7,
                    'khong_van_hanh_24_7', d.khong_van_hanh_24_7,
                    'phan_loai_ke_hoach_2959', d.phan_loai_ke_hoach_2959
                ) end,
                'co_gcn', exists (
                    select 1
                    from public.du_lieu_gcn g
                    where g.madvhc_soto_sothua
                        = t.ma_xa || '_' || t.so_to::text || '_' || t.so_thua::text
                )
            )
        ) as feature
        from public.thua_dat t
        left join public.dong_bo_du_lieu d
            on d.ma_xa = t.ma_xa and d.so_to = t.so_to and d.so_thua = t.so_thua
        where t.ma_xa = p_ma_xa
          and (p_so_to is null or t.so_to = p_so_to)
          and (p_so_thua is null or t.so_thua = p_so_thua)
          and (
              p_nhom is null or array_length(p_nhom, 1) is null
              or (
                  'DEFAULT' = any(p_nhom)
                  and (d.id is null or coalesce(trim(d.phan_loai_ke_hoach_2959), '') = '')
              )
              or upper(trim(d.phan_loai_ke_hoach_2959)) in (
                  select upper(trim(x)) from unnest(p_nhom) as x
              )
          )
        order by t.so_to, t.so_thua
        limit p_limit offset p_offset
    ) features;
$$;

grant execute on function public.search_parcels(
    text, text[], integer, integer, integer, integer, double precision
) to anon, authenticated;

-- Danh sách nguồn Google Sheet cho công cụ đồng bộ GCN (sync_gcn/).
-- Quản lý qua trang "Nhập đường link" trên web (backend dùng Service
-- Role Key), sync_gcn/main.py đọc bảng này thay vì file Excel local.
create table if not exists public.nguon_gcn (
    ma_nguon text primary key,
    ten_nguon text not null default '',
    url text not null,
    kich_hoat boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.nguon_gcn enable row level security;

-- Không tạo policy nào: chỉ Service Role Key (backend Flask) đọc/ghi
-- được bảng này, anon/authenticated không truy cập trực tiếp qua
-- PostgREST vì đây là dữ liệu cấu hình quản trị.

-- =========================================================
-- THỐNG KÊ THU THẬP DỮ LIỆU GCN THEO XÃ/PHƯỜNG
-- Dùng cho trang dashboard (GcnDashboardPage.jsx) — số thửa đã "nhập
-- biểu" (có dữ liệu GCN, đối chiếu qua khóa madvhc_soto_sothua, giống
-- co_gcn trong get_parcels_in_view/search_parcels) trên tổng số thửa,
-- theo từng xã. Gộp theo khóa DISTINCT trước khi LEFT JOIN (thay vì
-- EXISTS tương quan từng dòng như get_parcels_in_view) vì hàm này quét
-- toàn bộ thua_dat chứ không giới hạn theo khung bản đồ/limit.
-- =========================================================

create or replace function public.gcn_thu_thap_theo_xa()
returns table (
    ma_xa text,
    tong_so_thua bigint,
    da_nhap_bieu bigint
)
language sql
stable
security definer
set search_path = public, extensions
as $$
    with gcn_keys as (
        select distinct g.madvhc_soto_sothua
        from public.du_lieu_gcn g
        where g.madvhc_soto_sothua is not null
    )
    select
        t.ma_xa,
        count(*)::bigint as tong_so_thua,
        count(k.madvhc_soto_sothua)::bigint as da_nhap_bieu
    from public.thua_dat t
    left join gcn_keys k
        on k.madvhc_soto_sothua = t.ma_xa || '_' || t.so_to::text || '_' || t.so_thua::text
    group by t.ma_xa
    order by t.ma_xa;
$$;

grant execute on function public.gcn_thu_thap_theo_xa() to anon, authenticated;

