create extension if not exists postgis with schema extensions;

create table if not exists public.thua_dat (
    id bigint generated by default as identity primary key,
    ma_xa text not null,
    so_to integer not null,
    so_thua integer not null,
    muc_dich_su_dung text,
    dien_tich double precision,
    ten_chu text,
    dia_chi text,
    geom extensions.geometry(Polygon, 4326) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint thua_dat_ma_xa_so_to_so_thua_key unique (ma_xa, so_to, so_thua)
);

create index if not exists thua_dat_geom_gix
    on public.thua_dat using gist (geom);

create index if not exists thua_dat_tra_cuu_idx
    on public.thua_dat (ma_xa, so_to, so_thua);

alter table public.thua_dat enable row level security;

drop policy if exists "Cho phép đọc thửa đất" on public.thua_dat;
create policy "Cho phép đọc thửa đất"
    on public.thua_dat
    for select
    to anon, authenticated
    using (true);

create table if not exists public.dong_bo_du_lieu (
    id bigint generated by default as identity primary key,
    ma_xa text not null,
    so_to integer not null,
    so_thua integer not null,
    da_xuat_so_dia_chinh_dien_tu boolean not null default false,
    chua_xuat_so_dia_chinh_dien_tu boolean not null default false,
    dong_bo_3_khoi boolean not null default false,
    khong_dong_bo_3_khoi boolean not null default false,
    chi_co_du_lieu_thuoc_tinh boolean not null default false,
    khop_csdlqg_dan_cu boolean not null default false,
    chua_khop_csdlqg_dan_cu boolean not null default false,
    khong_xac_dinh_csdlqg_dan_cu boolean not null default false,
    van_hanh_24_7 boolean not null default false,
    khong_van_hanh_24_7 boolean not null default false,
    phan_loai_ke_hoach_2959 text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint dong_bo_du_lieu_ma_xa_so_to_so_thua_key unique (ma_xa, so_to, so_thua),
    constraint dong_bo_du_lieu_thua_dat_fkey
        foreign key (ma_xa, so_to, so_thua)
        references public.thua_dat (ma_xa, so_to, so_thua)
        on delete cascade
);

create index if not exists dong_bo_du_lieu_tra_cuu_idx
    on public.dong_bo_du_lieu (ma_xa, so_to, so_thua);

alter table public.dong_bo_du_lieu enable row level security;

drop policy if exists "Cho phép đọc đồng bộ dữ liệu" on public.dong_bo_du_lieu;
create policy "Cho phép đọc đồng bộ dữ liệu"
    on public.dong_bo_du_lieu
    for select
    to anon, authenticated
    using (true);

