-- Bảng dữ liệu GCN đồng bộ từ Google Sheet.
-- CHỈ thêm bảng mới, không đụng tới thua_dat/dong_bo_du_lieu hay bất kỳ
-- bảng WebGIS nào khác. Chạy file này trong Supabase SQL Editor của
-- project WebGIS hiện tại (không tạo project Supabase mới).

-- Chuẩn hóa số tờ/số thửa lấy từ Google Sheet (kiểu text, có thể dính
-- khoảng trắng, số 0 ở đầu, hoặc đuôi ".0" do Sheets xuất số) về đúng
-- dạng số nguyên dạng text, để so khớp được với so_to/so_thua kiểu
-- integer bên bảng thua_dat. Giữ nguyên (chỉ trim) nếu không phải số,
-- vì madvhc là mã đơn vị hành chính — số 0 ở đầu có ý nghĩa, không được
-- chuẩn hóa qua hàm này.
create or replace function public.normalize_so_text(p_value text)
returns text
language plpgsql
immutable
as $$
declare
  v text := trim(coalesce(p_value, ''));
begin
  if v = '' then
    return null;
  end if;

  if v ~ '^[0-9]+(\.[0-9]+)?$' then
    return trunc(v::numeric)::bigint::text;
  end if;

  return v;
end;
$$;

create table if not exists public.du_lieu_gcn (
  id bigint generated by default as identity primary key,

  -- Thông tin nguồn (khớp 1 dòng trong danh_sach_sheet.xlsx).
  ma_nguon text not null,
  ten_nguon text,
  sheet_url text,
  dong_sheet integer,
  synced_at timestamptz,
  created_at timestamptz not null default now(),

  -- 56 trường lấy nguyên văn từ Google Sheet ("Trang tính1"!B4:BE, theo
  -- đúng thứ tự cột B..BE — dữ liệu thật bắt đầu từ dòng 4, không phải
  -- dòng 3 như dự kiến ban đầu). Giữ kiểu text ở bản đầu để không mất số
  -- 0 đầu ở CCCD/mã định danh/số giấy tờ và tránh sai lệch định dạng.
  madvhc text,
  sophathanhgcn text,
  ngaycapgcn text,
  sovaosogcn text,
  tentochuc text,
  madinhdanhtochuc text,
  hovatenchusudung text,
  ngaythangnamsinh text,
  gioitinh text,
  sodinhdanhcanhan text,
  diachithuongtru text,
  phapnhantrengcn text,
  vaitrophapnhan text,
  tenchusudunghientai text,
  sodinhdanh_chusudunghientai text,
  diachi_chusudunghientai text,
  lydothaydoi text,
  madinhdanhthuadat text,
  soto_gcn text,
  sothua_gcn text,
  soto text,
  sothua text,
  diachi_thuadat text,
  dientichthuadat text,
  loaidat1 text,
  dientich1 text,
  nguongoc1 text,
  hinhthucsudung1 text,
  thoihansudung1 text,
  loaidat2 text,
  dientich2 text,
  nguongoc2 text,
  hinhthucsudung2 text,
  thoihansudung2 text,
  loaidat3 text,
  dientich3 text,
  nguongoc3 text,
  hinhthucsudung3 text,
  thoihansudung3 text,
  loaitaisan text,
  khunhachungcu_honhop text,
  nhachungcu text,
  socanho text,
  dientichxaydung text,
  dientichsan text,
  hinhthucsohuu text,
  thoihansohuu text,
  caphang text,
  tenfilequet text,
  sogiayto1 text,
  loaigiayto1 text,
  sogiayto2 text,
  loaigiayto2 text,
  hosoquet text,
  guild text,
  phanloai text
);

-- Năm sinh người sử dụng hiện tại (trường hợp không phải chủ sử dụng pháp
-- lý trên GCN — do thừa kế/tặng cho/chuyển nhượng chưa cập nhật GCN).
-- Dữ liệu gốc từ Google Sheet (sync_gcn/) không có cột này, luôn NULL —
-- chỉ biểu Nhóm 4 mới ghi (chỉ nhập NĂM, không phải ngày đầy đủ, khác quy
-- ước "ngày sinh" của chủ sử dụng pháp lý — xem nhom4_service.py).
alter table public.du_lieu_gcn
  add column if not exists ngaysinh_chusudunghientai text;

-- Khóa ghép madvhc + số tờ + số thửa (đã chuẩn hóa) để đối chiếu 1-1 với
-- (ma_xa, so_to, so_thua) bên bảng thua_dat — dùng kiểm tra thửa nào đã
-- có dữ liệu GCN (xem get_parcels_in_view/search_parcels trong
-- supabase/schema.sql).
alter table public.du_lieu_gcn
  add column if not exists madvhc_soto_sothua text
  generated always as (
    trim(coalesce(madvhc, ''))
    || '_' || coalesce(public.normalize_so_text(soto), '')
    || '_' || coalesce(public.normalize_so_text(sothua), '')
  ) stored;

-- Cột riêng cho nguồn "biểu Nhóm 4" (trang /nhom-4, backend ghi thẳng vào
-- đây thay vì bảng riêng — xem backend/app/services/nhom4_service.py).
-- Dữ liệu từ Google Sheet (sync_gcn/) không có các cột này, luôn NULL.
alter table public.du_lieu_gcn
  add column if not exists ghichu text;

alter table public.du_lieu_gcn
  add column if not exists submission_id uuid;

alter table public.du_lieu_gcn
  add column if not exists file_chinh_drive_id text;

alter table public.du_lieu_gcn
  add column if not exists file_chinh_ten_file text;

alter table public.du_lieu_gcn
  add column if not exists file_phu_drive_id text;

alter table public.du_lieu_gcn
  add column if not exists file_phu_ten_file text;

create index if not exists idx_du_lieu_gcn_ma_nguon
  on public.du_lieu_gcn (ma_nguon);

create index if not exists idx_du_lieu_gcn_madvhc
  on public.du_lieu_gcn (madvhc);

drop index if exists public.idx_du_lieu_gcn_madvhc_soto_sothua;

create index if not exists idx_du_lieu_gcn_madvhc_soto_sothua_key
  on public.du_lieu_gcn (madvhc_soto_sothua);

create index if not exists idx_du_lieu_gcn_sophathanhgcn
  on public.du_lieu_gcn (sophathanhgcn);

alter table public.du_lieu_gcn enable row level security;

-- Mặc định KHÔNG tạo policy nào: bật RLS mà không có policy nghĩa là
-- chỉ Service Role Key (bỏ qua RLS, dùng trong sync_gcn) mới đọc/ghi
-- được — anon/authenticated không truy cập được qua PostgREST.
--
-- Chỉ bỏ comment đoạn dưới nếu sau này WebGIS (frontend, dùng anon key)
-- cần SELECT trực tiếp bảng này:
--
-- create policy "du_lieu_gcn_select_anon"
--   on public.du_lieu_gcn
--   for select
--   to anon, authenticated
--   using (true);

-- Bảng "giữ chỗ" nguyên tử cho biểu Nhóm 4 — chặn race 2 request nộp
-- CÙNG 1 thửa gần như đồng thời (double-click, mở 2 tab, nộp lại khi
-- chưa chắc lần trước có thành công...) lọt qua kiểm tra
-- list_existing_keys() trong nhom4_service.py: kiểm tra đó đọc rồi mới
-- quyết định, KHÔNG an toàn khi 2 request chạy song song (cả 2 có thể
-- cùng đọc thấy "chưa có" trước khi request nào kịp ghi) — dẫn tới 1 bộ
-- hồ sơ bị ghi 2 lần + PDF bị đẩy lên Drive 2 lần. UNIQUE constraint +
-- xử lý trong 1 transaction Postgres (RPC dưới đây) đảm bảo chỉ 1 request
-- thắng, request còn lại nhận lỗi rõ ràng.
create table if not exists public.nhom4_thua_da_nop (
  khoa text primary key,
  created_at timestamptz not null default now()
);
alter table public.nhom4_thua_da_nop enable row level security;
-- Không tạo policy: chỉ Service Role Key mới đọc/ghi được.

create or replace function public.nhom4_claim_keys(p_keys text[])
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_distinct_count int;
  v_inserted_count int;
begin
  select count(distinct k) into v_distinct_count from unnest(p_keys) as k;

  insert into public.nhom4_thua_da_nop (khoa)
  select distinct k from unnest(p_keys) as k
  on conflict (khoa) do nothing;

  get diagnostics v_inserted_count = row_count;

  if v_inserted_count <> v_distinct_count then
    raise exception 'Một hoặc nhiều thửa trong hồ sơ này vừa được nộp trùng lúc — vui lòng tải lại trang và kiểm tra trước khi nộp lại.';
  end if;
end;
$$;
revoke all on function public.nhom4_claim_keys(text[]) from public;
grant execute on function public.nhom4_claim_keys(text[]) to service_role;
