-- Bảng dữ liệu GCN đồng bộ từ Google Sheet.
-- CHỈ thêm bảng mới, không đụng tới thua_dat/dong_bo_du_lieu hay bất kỳ
-- bảng WebGIS nào khác. Chạy file này trong Supabase SQL Editor của
-- project WebGIS hiện tại (không tạo project Supabase mới).

create table if not exists public.du_lieu_gcn (
  id bigint generated by default as identity primary key,

  -- Thông tin nguồn (khớp 1 dòng trong danh_sach_sheet.xlsx).
  ma_nguon text not null,
  ten_nguon text,
  sheet_url text,
  dong_sheet integer,
  synced_at timestamptz,
  created_at timestamptz not null default now(),

  -- 57 trường lấy nguyên văn từ Google Sheet ("Trang tính1"!B4:BF, theo
  -- đúng thứ tự cột B..BF — dữ liệu thật bắt đầu từ dòng 4, không phải
  -- dòng 3 như dự kiến ban đầu, và sheet có 57 cột chứ không phải 56 vì
  -- có thêm cột "Ngày sinh người sử dụng hiện tại"). Giữ kiểu text ở
  -- bản đầu để không mất số 0 đầu ở CCCD/mã định danh/số giấy tờ và
  -- tránh sai lệch định dạng.
  madvhc text,
  sophathanhgcn text,
  ngaycapgcn text,
  sovaosogcn text,
  tentochuc text,
  madinhdanhtochuc text,
  hovatenchusudung text,
  ngaythangnamsinh text,
  gioitinh text,
  sodinhdanhcanhan text,
  diachithuongtru text,
  phapnhantrengcn text,
  vaitrophapnhan text,
  tenchusudunghientai text,
  ngaysinh_chusudunghientai text,
  sodinhdanh_chusudunghientai text,
  diachi_chusudunghientai text,
  lydothaydoi text,
  madinhdanhthuadat text,
  soto_gcn text,
  sothua_gcn text,
  soto text,
  sothua text,
  diachi_thuadat text,
  dientichthuadat text,
  loaidat1 text,
  dientich1 text,
  nguongoc1 text,
  hinhthucsudung1 text,
  thoihansudung1 text,
  loaidat2 text,
  dientich2 text,
  nguongoc2 text,
  hinhthucsudung2 text,
  thoihansudung2 text,
  loaidat3 text,
  dientich3 text,
  nguongoc3 text,
  hinhthucsudung3 text,
  thoihansudung3 text,
  loaitaisan text,
  khunhachungcu_honhop text,
  nhachungcu text,
  socanho text,
  dientichxaydung text,
  dientichsan text,
  hinhthucsohuu text,
  thoihansohuu text,
  caphang text,
  tenfilequet text,
  sogiayto1 text,
  loaigiayto1 text,
  sogiayto2 text,
  loaigiayto2 text,
  hosoquet text,
  guild text,
  phanloai text
);

-- An toàn chạy lại nếu bảng đã tồn tại từ trước (lúc chưa có cột này):
alter table public.du_lieu_gcn
  add column if not exists ngaysinh_chusudunghientai text;

create index if not exists idx_du_lieu_gcn_ma_nguon
  on public.du_lieu_gcn (ma_nguon);

create index if not exists idx_du_lieu_gcn_madvhc
  on public.du_lieu_gcn (madvhc);

create index if not exists idx_du_lieu_gcn_madvhc_soto_sothua
  on public.du_lieu_gcn (madvhc, soto, sothua);

create index if not exists idx_du_lieu_gcn_sophathanhgcn
  on public.du_lieu_gcn (sophathanhgcn);

alter table public.du_lieu_gcn enable row level security;

-- Mặc định KHÔNG tạo policy nào: bật RLS mà không có policy nghĩa là
-- chỉ Service Role Key (bỏ qua RLS, dùng trong sync_gcn) mới đọc/ghi
-- được — anon/authenticated không truy cập được qua PostgREST.
--
-- Chỉ bỏ comment đoạn dưới nếu sau này WebGIS (frontend, dùng anon key)
-- cần SELECT trực tiếp bảng này:
--
-- create policy "du_lieu_gcn_select_anon"
--   on public.du_lieu_gcn
--   for select
--   to anon, authenticated
--   using (true);
